[build]
  publish = "public"
  functions = "api"
  environment = { CHROME = "local" }
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[context.production]
  environment = { CHROME = "aws" }